### PR TITLE
Alan Yu and Savana Hughes Pull Request

### PR DESCRIPTION
**Pull request by SavvyTechGal**
Savana Hughes: Magic Sqaure
Alan Yu: Prime Generate

### CODE REVIEW

**Comment by ArielAvshalom** [comment]
You all have a conflict on your fork. Looks like you updated team two's readme?  You can try figuring it out with the git cli or by removing the file in question from your commit.

**Comment by ArielAvshalom** [comment]
There are still conflicts here. Check out the Git Stack command and Git diff

**Comment by ArielAvshalom** [comment]
Specifically the conflicts are Team1 readme and Team2 readme. I suggest that you remove them from your commit and ship it again.

**Comment by SavvyTechGal** [comment]
Merge conflicts have been resolved

**Comment by ArielAvshalom** [comment]
Sweet!

**Pull request merged**
